version: '3.8'

services:
    app:
      build:
        context: .
      ports:
        - '8080:8080'
      depends_on:
        - db
    db:
      image: postgres:15
      ports:
        - '5433:5432'
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root
      volumes:
        - db-data:/var/lib/postgresql/data


volumes:
  db-data: {}